import Head from 'next/head'
import styles from '../../styles/Home.module.css';

function Tanden() {
	return (
		<div className={styles.container}>
			<Head>
				<title>App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<p className={styles.description}>
					Edit <code>src/tanden.jsx</code> and save to reload.
				</p>
				<a
					className={styles.card}
					href="https://reactjs.org"
					target="_blank"
					rel="noopener noreferrer"
				>
					Learn React
				</a>
			</main>
		</div>
	);
}

export default Tanden;